<a href="https://colab.research.google.com/github/Vassudev22/EDA-Lab-L41-L42-/blob/main/handling_missing_data%20%26%20Imputation_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as pd
import pandas as pd
data = np.arange (15,30).reshape(5,3)
dfx = pd.DataFrame(data, index=['maths', 'physics', 'chemistry','biology',"csc"],
columns=['exam1', 'exam2', 'exam3'])
dfx

           exam1  exam2  exam3
maths         25     26     27
physics       28     29     30
chemistry     31     32     33
biology       34     35     36
csc           37     38     39

In [14]:
dfx['exam4'] = np.nan
dfx.loc['english'] = np.arange(15, 20)
dfx.loc['probability'] = np.nan
dfx['exam5'] = np.nan

dfx['exam4']['dis'] = 20.
dfx

/tmp/ipykernel_941/2824891810.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['exam4']['dis'] = 20.

             exam1  exam2  exam3  exam4  exam5
maths         25.0   26.0   27.0    NaN    NaN
physics       28.0   29.0   30.0    NaN    NaN
chemistry     31.0   32.0   33.0    NaN    NaN
biology       34.0   35.0   36.0    NaN    NaN
csc           37.0   38.0   39.0    NaN    NaN
english       15.0   16.0   17.0   18.0    NaN
probability    NaN    NaN    NaN    NaN    NaN

In [18]:
dfx['exam4'] = np.nan
dfx.loc['probability'] = np.nan
dfx['exam5'] = np.nan
dfx.loc['english'] = np.arange(15, 20)
dfx['exam4']['maths'] = 20.
dfx

/tmp/ipykernel_941/2675783406.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['exam4']['maths'] = 20.

             exam1  exam2  exam3  exam4  exam5
maths         25.0   26.0   27.0   20.0    NaN
physics       28.0   29.0   30.0    NaN    NaN
chemistry     31.0   32.0   33.0    NaN    NaN
biology       34.0   35.0   36.0    NaN    NaN
csc           37.0   38.0   39.0    NaN    NaN
english       15.0   16.0   17.0   18.0   19.0
probability    NaN    NaN    NaN    NaN    NaN

In [20]:
dfx.isnull()
dfx.notnull()

             exam1  exam2  exam3  exam4  exam5
maths         True   True   True   True  False
physics       True   True   True  False  False
chemistry     True   True   True  False  False
biology       True   True   True  False  False
csc           True   True   True  False  False
english       True   True   True   True   True
probability  False  False  False  False  False

In [23]:
dfx.isnull().sum()

exam1    1
exam2    1
exam3    1
exam4    5
exam5    6
dtype: int64

In [24]:
dfx.isnull().sum().sum()

np.int64(14)

In [25]:
dfx.count()

exam1    6
exam2    6
exam3    6
exam4    2
exam5    1
dtype: int64

In [26]:
dfx.exam4[dfx.exam4.notnull()]

maths      20.0
english    18.0
Name: exam4, dtype: float64

In [27]:
dfx.exam4.dropna()

maths      20.0
english    18.0
Name: exam4, dtype: float64

In [28]:
dfx.dropna()

         exam1  exam2  exam3  exam4  exam5
english   15.0   16.0   17.0   18.0   19.0

In [29]:
dfx.dropna(how='all')

           exam1  exam2  exam3  exam4  exam5
maths       25.0   26.0   27.0   20.0    NaN
physics     28.0   29.0   30.0    NaN    NaN
chemistry   31.0   32.0   33.0    NaN    NaN
biology     34.0   35.0   36.0    NaN    NaN
csc         37.0   38.0   39.0    NaN    NaN
english     15.0   16.0   17.0   18.0   19.0

In [30]:
dfx.dropna(how='all', axis=1)

             exam1  exam2  exam3  exam4  exam5
maths         25.0   26.0   27.0   20.0    NaN
physics       28.0   29.0   30.0    NaN    NaN
chemistry     31.0   32.0   33.0    NaN    NaN
biology       34.0   35.0   36.0    NaN    NaN
csc           37.0   38.0   39.0    NaN    NaN
english       15.0   16.0   17.0   18.0   19.0
probability    NaN    NaN    NaN    NaN    NaN

In [31]:
dfx.dropna(thresh=5, axis=1)

             exam1  exam2  exam3
maths         25.0   26.0   27.0
physics       28.0   29.0   30.0
chemistry     31.0   32.0   33.0
biology       34.0   35.0   36.0
csc           37.0   38.0   39.0
english       15.0   16.0   17.0
probability    NaN    NaN    NaN

In [35]:
filledDf = dfx.fillna(0)
filledDf

             exam1  exam2  exam3  exam4  exam5
maths         25.0   26.0   27.0   20.0    0.0
physics       28.0   29.0   30.0    0.0    0.0
chemistry     31.0   32.0   33.0    0.0    0.0
biology       34.0   35.0   36.0    0.0    0.0
csc           37.0   38.0   39.0    0.0    0.0
english       15.0   16.0   17.0   18.0   19.0
probability    0.0    0.0    0.0    0.0    0.0

In [36]:
dfx.mean()
filledDf.mean()

exam1    24.285714
exam2    25.142857
exam3    26.000000
exam4     5.428571
exam5     2.714286
dtype: float64

In [42]:
dfx.exam4.fillna(method='ffill')
dfx.exam4.fillna(method='bfill')

/tmp/ipykernel_941/4258376561.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.exam4.fillna(method='ffill')
/tmp/ipykernel_941/4258376561.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.exam4.fillna(method='bfill')

maths          20.0
physics        18.0
chemistry      18.0
biology        18.0
csc            18.0
english        18.0
probability     NaN
Name: exam4, dtype: float64

In [49]:
#IMPUTATION_TECHNIQUES
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

df = pd.DataFrame(
 {
 "Age": [25, np.nan, 30, 45, 22],
 "Salary": [50000, 60000, np.nan, 80000, 45000],
 "Category": ["A", "B", "A", np.nan, "B"],
 }
)
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])
df

    Age   Salary Category  Age_Mean
0  25.0  50000.0        A      25.0
1   NaN  60000.0        B      30.5
2  30.0      NaN        A      30.0
3  45.0  80000.0      NaN      45.0
4  22.0  45000.0        B      22.0

In [50]:
median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])
df

    Age   Salary Category  Age_Mean  Salary_Median
0  25.0  50000.0        A      25.0        50000.0
1   NaN  60000.0        B      30.5        60000.0
2  30.0      NaN        A      30.0        55000.0
3  45.0  80000.0      NaN      45.0        80000.0
4  22.0  45000.0        B      22.0        45000.0

In [54]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df[["Category_Mode"]] = mode_imputer.fit_transform(df[["Category"]])
print(df)

    Age   Salary Category  Age_Mean  Salary_Median   Age_MICE   Salary_MICE  \
0  25.0  50000.0        A      25.0        50000.0  25.000000  50000.000000
1   NaN  60000.0        B      30.5        60000.0  31.766487  60000.000000
2  30.0      NaN        A      30.0        55000.0  30.000000  57324.583367
3  45.0  80000.0      NaN      45.0        80000.0  45.000000  80000.000000
4  22.0  45000.0        B      22.0        45000.0  22.000000  45000.000000

  Category_Mode
0             A
1             B
2             A
3             A
4             B

In [52]:
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
print(df)

    Age   Salary Category  Age_Mean  Salary_Median   Age_MICE   Salary_MICE
0  25.0  50000.0        A      25.0        50000.0  25.000000  50000.000000
1   NaN  60000.0        B      30.5        60000.0  31.766487  60000.000000
2  30.0      NaN        A      30.0        55000.0  30.000000  57324.583367
3  45.0  80000.0      NaN      45.0        80000.0  45.000000  80000.000000
4  22.0  45000.0        B      22.0        45000.0  22.000000  45000.000000